default:
  port: 4000
  redisServerIp: '10.29.3.221'
  redisServerPort: '6379'
  CIServer: 'http://10.29.3.221:8080'
  jobName: 'TASK-RUNNER'
  nginxServer: 'http://10.29.3.221:8888/fs'
  taskServer: 'http://10.29.3.187' #更改为连接data时,你电脑的ip地址
