mysql:
  build: ./mysql
  ports:
    - "13306:3306"
  env_file: test.env
  environment:
    - LANG=C.UTF-8
    - TERM=dumb
# api-server:
#   build: ./api-server
#   links:
#     - mysql
jenkins:
  image: jenkins:1.625.3
  ports:
    - "8080:8080"
  volumes:
    - /var/jenkins_home
  links:
    - mysql
  environment:
    - LANG=C.UTF-8
    - TERM=dumb
