mongodb:
  build: ./mongodb
  volumes:
    - /home/ubuntu/works/recruiting-system/mongodb/data-db:/data/db
node-app:
  build: ./nodejs
  ports:
    - "3000:3000"
  volumes:
    - /home/ubuntu/works/recruiting-system/app:/var/app
  command: bash -c "cd /var/app && node app.js"
  links:
    - mongodb:mongodb
    - jetty-api:jetty-api
  env_file:
    - ./node.env
mysql:
  build: ./mysql
  environment:
    - LANG=C.UTF-8
    - TERM=dumb
  volumes:
    - /tmp/mysql:/var/lib/mysql
  command: mysqld
  environment:
    - MYSQL_RANDOM_ROOT_PASSWORD=1
jetty-api:
  image: jetty:9.3-jre8
  volumes:
    - ./release/jetty/webapps:/var/lib/jetty/webapps
#jenkins:
#  image: jenkins:1.625.3
#  ports:
#    - "8080:8080"
#  volumes:
#    - /Users/Thoughtworks/works/docker-cached/jenkins_home:/var/jenkins_home
#  links:
#    - mysql
#  environment:
#    - LANG=C.UTF-8
#    - TERM=dumb
#redis:
#  image: redis:3.0.7
#  ports:
#    - "6379:6379"
#  volumes:
#    - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
#nginx:
#  build: ./nginx
#  ports:
#    - "80:80"
#  environment:
#    - LANG=C.UTF-8
#    - TERM=dumb
#  volumes:
#    - ./nginx/conf.d:/etc/nginx/conf.d
#    - /Users/Thoughtworks/works/docker-cached/nginx_fs:/var/fs
#
#task-queue-node:
#  image: node:5.7.0-wheezy
#  ports:
#    - "4000:4000"
#  volumes:
#    - /Users/Thoughtworks/works/recruiting-system/task-queue:/var/task-queue
#  command: bash -c "cd /var/task-queue/ && npm install && node app"
#
#mongodb:
#  build: ./mongodb
#  ports:
#    - "27017:27017"
#    - "28017:28017"
#  environment:
#    - MONGODB_USER=tw
#    - MONGODB_DATABASE=twars
#    - MONGODB_PASS=hahahaha
#  volumes:
#    - /data:/data
