default:
  port: 3000
  database: 'mongodb://mongodb/twars'
  apiServer: 'http://jetty-api:8080/api/'
  appServer: 'http://node-app:3000/'
  taskServer: 'http://task-queue:4000/'
  sessionTtl: 3600 # 60(MINUTE_PER_HOUR) * 60(SECONDS_PER_MINUTE)
  staticFileServer: 'http://10.29.3.221:8888/fs/'
  domainName: 'localhost:'
  emailAccount: 'twarss@163.com'
  emailPassword: 'ssww123456'
  gitHubToken: 'Basic dHdhcnM6c3cxMjM0NTY3OA=='
test:
  port: 5000