default:
  port: 4000
  redisServerIp: 'redis'
  redisServerPort: '6379'
  CIServer: 'http://jenkins-nodejs:8080'
  jobName: 'TASK-RUNNER'
  nginxServer: 'http://nginx:8888/fs'
  taskServer: 'http://172.17.0.8'
